### PR TITLE
Update ppin.json

### PR DESCRIPTION
**Pull request by Fafrin**
+ new twitter

### CODE REVIEW

**Comment by collentine** [comment]
@Putr is this possible? Believe it's enough just listing the official accounts, not sure we should add inofficial ones...

**Comment by Fafrin** [comment]
Im actually not sure witch one is more official.

**Comment by Putr** [comment]
While this will work, it's not the most elegant way.

If we really wish to add "other" accounts, than use the array notation

    "twitter": {
        "username": "
        "others": ["PiratePIN", "OtherTw"]
    },`

**Comment by Fafrin** [comment]
So like this?

**Comment by Putr** [comment]
Yeah, that works

**Pull request merged**
