### PR TITLE
Update of PP-CZ

### PR DESCRIPTION
**Pull request by lnovy**
Please squash our commits :)

### CODE REVIEW

**Comment by Putr** [comment]
Merged. Squash would have been better, but I'm too lazy for that :)

**Comment by Putr** [comment]
Note: It seems the long/lat for the headquarters was switched. Now, I don't know if this is because i screwed up in the code or you switched the params. Could you check (I'm just running out).

Anyway, I've updated the dataset on production:
http://api.piratetimes.net/party/ppcz

**Comment by lnovy** [comment]
Yep, I've checked them only by copy-pasting to maps and it just switched them for me automagicaly, hidding the issue from me. Thanks!

**Comment by lnovy** [comment]
Huh, now it points into the sea, anyway the correct location is here:

https://www.google.cz/maps/place/%C5%98eho%C5%99ova+943%2F19,+%C5%BDi%C5%BEkov,+130+00+Praha-Praha+3/@50.0863825,14.4422069,13z/data=!4m2!3m1!1s0x470b9497a149df27:0x7d41e47e894dce6b

**Pull request merged**
