### PR TITLE
add ppeu to membership

### PR DESCRIPTION
**Pull request by PeterTheOne**

### CODE REVIEW

**Comment by PeterTheOne** [comment]
How do can we add observer memberships?

**Comment by Putr** [comment]
Hmm, good question. I'm in the middle of writing the specification for the json dataset. 

We can either add a new key `observerMemberships` but that does not seem clean. We should probably change the dataset as it is now so it's not "true/false" but "full/observer ..." and allow future proofit like that. I can write a migration script for all the data.

**Comment by PeterTheOne** [comment]
nice, second option sounds better to me.

**Comment by Croydon** [comment]
More or less off topic: I was wondering all the time why nobody takes care of the http://ppeu.net website...
But when https://europeanpirates.eu is the new one...
If ppeu.net is dead there should be a redirection to the new one. So if somebody has contacts to the admins there or has some more information.. :)

**Comment by Putr** [comment]
@PeterTheOne 
Agreed, I'll do the second one. Should not be too hard.

**Pull request merged**
